# Generated by Django 4.0.1 on 2022-01-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosm_app', '0002_producttypes_product_type_plural'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTypes',
            new_name='ProductType',
        ),
    ]
