# Generated by Django 4.0.1 on 2022-01-29 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosm_app', '0003_rename_producttypes_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product_types',
        ),
        migrations.AlterField(
            model_name='producer',
            name='product_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosm_app.producttype'),
        ),
    ]
