# Generated by Django 4.0.3 on 2022-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosm_app', '0008_treatment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
